### ISSUE TITLE
For the basis translation etc. it does not recognize "FormFlavor", but it works with "formflavor".

### ISSUE THREAD

**Issue by jackypheno** [wcxf/wcxf-python#11] opened 2017-12-19 05:59 UTC

**Comment by DavidMStraub** [comment] 2017-12-19 07:59
Hi,

that's right, but I believe it's not a bug. It's the name the developers gave to the basis in the basis file and it's consistent with the [documentation here](https://wcxf.github.io/bases.html#basis-formflavor). Or do you think it should be renamed, @jaredaevans?

**Comment by jaredaevans** [comment] 2017-12-19 16:47
Yes, that was the name we gave - sorry for any confusion.  We use the lowercase version everywhere to describe the basis name, although there is one ambiguous reference in the public document to the FormFlavor basis (which is referring to the manual).  Unless there is some reason it should be changed, I think it is fine.

**Comment by DavidMStraub** [comment] 2017-12-19 20:13
OK very good. Closing.

**Closed by DavidMStraub** 2017-12-19 20:13 UTC
